sudo: required
services:
  - docker
language: bash

jobs:
  include:
    - stage: build ARM image
      script:
      - ./create_dockerfiles.sh
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -t distribrewed/base:arm -f Dockerfile.arm .
      - docker run -t distribrewed/base:arm python --version
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - docker push distribrewed/base:arm