sudo: required
services:
  - docker
language: bash

branches:
  only:
    - master

jobs:
  include:
    - stage: Build image
      env: ARCH=x64
      env: BASE=alpine:3.6
      script:
      - ./travis_scripts/build_$ARCH.sh
    - stage: Build image
      env: ARCH=arm
      env: BASE=hypriot/rpi-alpine:3.6
      script:
      - ./travis_scripts/build_$ARCH.sh
    - stage: Trigger builds
      env: REPO=distribrewed/core
      script:
      - ./travis_scripts/trigger_builds.sh